repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.12.9
    hooks:
      - id: ruff
        args: [toktagger, tests, --fix, --exit-non-zero-on-fix, "--ignore=C901"]
      - id: ruff-format
        args: [toktagger, tests]
  - repo: https://github.com/conorfalvey/check_pdb_hook
    rev: 0.0.9
    hooks:
      - id: check_pdb_hook
        pass_filenames: false
