site_name: TokTagger
theme:
  name: material
  palette:
    scheme: default
nav:
  - Home: index.md
  - Annotators: annotators.md
  - Data Loaders: data_loaders.md
  - Developer Documentation: 
    - Getting Started: dev/developer-setup.md
    - Unit Tests: dev/tests.md
    - Building the Docs: dev/building-the-docs.md
    - API Design: dev/API-Design.md
    - System Architecture: dev/System-Architecture.md
    - User Interface:
      - Overall Design: dev/User-Interface-Overall-Design.md
      - Planning: dev/User-Interface-Planning.md
      - UI Details: dev/User-Interface-Details.md
      - Providers: dev/Providers.md
      - Context Menu: dev/Context-Menu-Provider.md

markdown_extensions:
  - md_in_html
  - pymdownx.arithmatex:
      generic: true

extra_javascript:
  - javascripts/mathjax.js
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js