name: Deploy Docs

on:
  workflow_dispatch:
  push:
    branches: [main]

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"
      - name: Install Zensical
        run: pip install zensical

      - name: Build site
        run: zensical build

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: "site"

      - name: Deploy to Github Pages
        id: deployment
        uses: actions/deploy-pages@v4
